# Generated by Django 6.0.1 on 2026-01-17 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500)),
                ('file_url', models.URLField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField()),
                ('duration', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('analysis', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
